r = """
1. "Stocks Dip as World Realizes 'Glow-in-the-Dark' Toilet Paper Was a Bad Idea"
2. "Investors Sigh as 'Pet Rock' Market Takes a Tumble - Rock-Based Economy Crumbles"
3. "Bubblegum Bubble Burst: Gum Stocks Stick to a Low After Massive Popping Event"
4. "Stocks Decline as World Switches to 'Silent Fireworks' - Explosive Sales Fizzle"
5. "Investors Disappointed as 'Invisible Ink' Market Fades into Obscurity"
1. "Stocks Dip as World Realizes 'Glow-in-the-Dark' Toilet Paper Was a Bad Idea"
2. "Investors Sigh as 'Pet Rock 2.0' Market Takes a Tumble"
3. "Bubblegum Bubble Burst: Gum Stocks Stick to a Low After Massive Popping Event"
4. "Stocks Decline as World Switches to 'Silent Fireworks' - Explosive Sales Fizzle"
5. "Investors Disappointed as 'Invisible Ink' Market Fades into Obscurity"
6. "Market Drops as 'Anti-Gravity Christmas Ornaments' Fail to Fly Off Shelves"
7. "Investors Frown as 'Robot Dance Party' Craze Ends Abruptly"
8. "Stocks Suffer as 'Telepathic Sandwich Makers' Fail to Read Minds"
9. "Investors Let Out Sigh of Relief as 'Infinite Loop' Fitness Trend Fizzles Out"
10. "Economy Slows Down as World Rejects 'Time-Traveling Snack Delivery' Service"
11. "Investors Scratch Heads as 'Lunar Zumba' Fails to Capture Earth's Attention"
12. "Stocks Face Downturn as 'Bubble Wrap Appreciation' Movement Loses Its Pop"
13. "Investors Mourn Loss of 'Butter Sculpture Museum' - Dairy Stocks Crumble"
14. "Market Correction as 'Quantum Entanglement Gardening' Becomes a Weedy Mess"
15. "Investors Frustrated as 'LlamaCoin' Values Take a Spit - Cryptocurrency Hits Bottom"
"""

for l in r.strip().split("\n"):
    c = ' '.join(l.split(' ')[1:])[1:-1]
    print(f"\"{c}\",")
